
# DISCLAIMER: This code was generated by Google Gemini (with lots of clear instruction and iterating) (You said we could!)

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import Circle

# 1. Generate Data
np.random.seed(42)
n_points = 1000
x = np.random.normal(0, 1, n_points)
y = np.random.normal(0, 1, n_points)

# 2. Define the Circle (center 1.5, 1.5, radius 1.0)
cx, cy, r = 1.5, 1.5, 1.0
x_start, x_end = cx - r, cx + r  # 0.5 and 2.5
y_start, y_end = cy - r, cy + r

dist = np.sqrt((x - cx)**2 + (y - cy)**2)
is_in_circle = dist <= r

# 3. Custom Binning to prevent "leaking"
# We ensure 0.5 and 2.5 are exact bin boundaries
bins = np.unique(np.concatenate([
    np.linspace(-3.5, x_start, 15),
    np.linspace(x_start, x_end, 10),
    np.linspace(x_end, 3.5, 5)
]))

# 4. Setup Layout
fig = plt.figure(figsize=(9, 9))
gs = fig.add_gridspec(2, 2, width_ratios=[4, 1], height_ratios=[1, 4],
                      wspace=0.05, hspace=0.05)

ax_main = fig.add_subplot(gs[1, 0])
ax_hist_x = fig.add_subplot(gs[0, 0], sharex=ax_main)
ax_hist_y = fig.add_subplot(gs[1, 1], sharey=ax_main)

# --- Main Scatter Plot ---
ax_main.scatter(x[~is_in_circle], y[~is_in_circle], color='#444444', s=10, alpha=0.7)
ax_main.scatter(x[is_in_circle], y[is_in_circle], color='#1fb5eb', s=12)

# Blue Circle & Label
circle_patch = Circle((cx, cy), r, color='#1fb5eb', fill=False, linewidth=2)
ax_main.add_patch(circle_patch)
circle_pct = (is_in_circle.sum() / n_points) * 100
ax_main.text(cx + 0.3, cy + 0.3, f'{circle_pct:.1f}%', 
             color='white', weight='bold', bbox=dict(facecolor='#1fb5eb', edgecolor='none'))

# Dotted guidelines inside scatter
ax_main.axvline(x_start, color='#1fb5eb', linestyle='--', alpha=0.5)
ax_main.axvline(x_end, color='#1fb5eb', linestyle='--', alpha=0.5)
ax_main.axhline(y_start, color='#1fb5eb', linestyle='--', alpha=0.5)
ax_main.axhline(y_end, color='#1fb5eb', linestyle='--', alpha=0.5)

# --- Top Histogram (X) ---
ax_hist_x.hist(x, bins=bins, color='#444444', rwidth=0.9)
ax_hist_x.hist(x[is_in_circle], bins=bins, color='#1fb5eb', rwidth=0.9)

ax_hist_x.axvline(x_start, color='#1fb5eb', linestyle='-', linewidth=1.5)
ax_hist_x.axvline(x_end, color='#1fb5eb', linestyle='-', linewidth=1.5)

# Centered X percentage label
x_slice_pct = ((x > x_start) & (x < x_end)).sum() / (n_points/100)
ax_hist_x.text((x_start + x_end)/2, 90, f'{x_slice_pct:.1f}%', 
               fontsize=14, ha='center', color='#333333')

# --- Right Histogram (Y) ---
ax_hist_y.hist(y, bins=bins, orientation='horizontal', color='#444444', rwidth=0.9)
ax_hist_y.hist(y[is_in_circle], bins=bins, orientation='horizontal', color='#1fb5eb', rwidth=0.9)

ax_hist_y.axhline(y_start, color='#1fb5eb', linestyle='-', linewidth=1.5)
ax_hist_y.axhline(y_end, color='#1fb5eb', linestyle='-', linewidth=1.5)

# Centered Y percentage label (moved to the right of the plot area)
y_slice_pct = ((y > y_start) & (y < y_end)).sum() / (n_points/100)
ax_hist_y.text(105, (y_start + y_end)/2, f'{y_slice_pct:.1f}%', 
               fontsize=14, va='center', color='#333333')

# --- Final Styling ---
ax_main.set_xlim(-3.5, 3.5)
ax_main.set_ylim(-3.5, 3.5)
ax_main.set_xlabel('x', fontsize=18, fontstyle='italic')
ax_main.set_ylabel('y', fontsize=18, rotation=0, labelpad=15, fontstyle='italic')

for ax in [ax_hist_x, ax_hist_y]:
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    if ax == ax_hist_x:
        plt.setp(ax.get_xticklabels(), visible=False)
    else:
        plt.setp(ax.get_yticklabels(), visible=False)

plt.show()